sudo: required
services:
  - docker

before_install:
  - docker build -t lschulzes/docker-vite-react-tests -f Dockerfile.dev .

script:
  - docker run lschulzes/docker-vite-react-tests yarn test -- --coverage
